ktor:
  deployment:
    port: "$CIVORIS_PORT:8080"
  application:
    modules:
      - me.bumiller.civoris.ApplicationKt.restApi

civoris:
  security:
    jwt:
      duration: "$CIVORIS_SECURITY_JWT_DURATION:15"
      secret: "$CIVORIS_SECURITY_JWT_SECRET"
    refresh:
      token:
        duration: "$CIVORIS_SECURITY_REFRESH_TOKEN_DURATION:15"
    email:
      token:
        duration: "$CIVORIS_SECURITY_EMAIL_TOKEN_DURATION:5"
  database:
    url: "$CIVORIS_DATABASE_URL"
    user: "$CIVORIS_DATABASE_USER"
    password: "$CIVORIS_DATABASE_PASSWORD"
  mail:
    host: "$CIVORIS_MAIL_HOST"
    port: "$CIVORIS_MAIL_PORT"
    ssl: "$CIVORIS_MAIL_SSL:true"
    password: "$CIVORIS_MAIL_PASSWORD"
    from: "$CIVORIS_MAIL_FROM"
  rest:
    path: "$CIVORIS_REST_PATH:/api/"
  web: "$CIVORIS_WEB_URL"