name: Build and Test

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up zulu/21 JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Run gradle build task
        run: ./gradlew build -x test
  Unit-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up zulu/21 JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Run gradle test task
        run: ./gradlew test
  Sonar-Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run gradle sonar task
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: ./gradlew sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=my-own-lawbook -Dsonar.projectKey=my-own-lawbook_server -Dsonar.token=$SONAR_TOKEN
