name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up zulu/21 JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Run gradle build task
        run: ./gradlew build -x test
  unit-test:
    name: Unit Tests and Sonar Analysis
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up zulu/21 JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Run gradle test task
        run: ./gradlew test

  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    needs: [ unit-test ]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
