name: Create GitHub Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  create-release:
    if: github.event.created # Only run this workflow when the branch is created

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ##- name: Build fat jar
      ##  run: ./gradlew buildFatJar

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          tag: ${{ steps.extract_branch.outputs.branch }}

      #- name: Create release
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    repository: my-own-lawbook/server
      #    files: ./build/libs/my-own-lawbook-all.jar
      #    body: Release body
      #    name: Release name