name: Create GitHub Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  create-release:
    if: github.event.created # Only run this workflow when the branch is created

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the fat jar
      - name: Build fat jar
        run: ./gradlew buildFatJar

      # Computes the name of the release (tag) and returns it into the output string
      - name: Extract tag name
        shell: bash
        run: |
          branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          tag_name=${branch_name:8}
          echo "tag=$tag_name" >> $GITHUB_OUTPUT
        id: extract_tag_name

      # Creates the tag for the release
      - name: Create Tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_tag_name.outputs.tag }}

      # Creates the release
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          repository: my-own-lawbook/server
          files: ./build/libs/my-own-lawbook-all.jar
          body_path: ./changelogs/${{ steps.extract_tag_name.outputs.tag }}.md
          body: <Create changelog>
          name: ${{ steps.extract_tag_name.outputs.tag }}
          tag_name: ${{ steps.extract_tag_name.outputs.tag }}
