name: Create GitHub Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_REPO: ${{ github.repository }}
  REGISTRY_ORG: ${{ github.repository_owner }}

jobs:
  create-release:
    if: github.event.created # Only run this workflow when the branch is created

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Computes the name of the release (tag) and returns it into the output string
      - name: Extract tag name
        shell: bash
        run: |
          branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          tag_name=${branch_name:8}
          echo "tag=$tag_name" >> $GITHUB_OUTPUT
        id: extract_tag_name

      - name: Install docker client
        shell: bash
        run: apt install docker.io

      - name: Log in to the Container registry
        shell: bash
        run: docker login $REGISTRY -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD

      - name: Build the Image
        shell: bash
        run: ./gradlew buildImage

      - name: Pull image to docker
        shell: bash
        run: docker image load < ./build/jib-image.tar

      - name: Tag local image
        shell: bash
        run: docker image tag my-own-lawbook $REGISTRY/$REGISTRY_ORG/$REGISTRY_REPO:${{ steps.extract_tag_name.outputs.tag }}

      - name: Push to Registry
        shell: bash
        run: docker push $REGISTRY/$REGISTRY_ORG/$REGISTRY_REPO:${{ steps.extract_tag_name.outputs.tag }}


